serenity.project.name=Serenity and Cucumber Quick Start
enable.markdown=story,narrative,scenario,step
feature.file.encoding=utf-8

# Screenshots
#serenity.take.screenshots=BEFORE_AND_AFTER_EACH_STEP
serenity.take.screenshots=FOR_EACH_ACTION

# Report output
serenity.outputDirectory=target/site/serenity

# Logging
serenity.verbose.steps=true
serenity.logging=VERBOSE

# Cucumber
serenity.use.unique.browser=false
