#
#Mon Mar 09 11:07:32 COT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-fullscreen, --test-type, --no-sandbox, --ignore-certificate-errors, \\r\\n                --disable-popup-blocking, --disable-default-apps, --disable-extensions-file-access-check, \\r\\n                  --incognito, --disable-infobars, --disable-gpu, --disable-dev-shm-usage], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
